Remove duplicate Pillow requirement
Having this specified twice causes the following error when installing
dependencies:

    ERROR: Double requirement given: Pillow==7.1.2 (from -r requirements.txt (line 4)) (already in Pillow==6.2.0 (from -r requirements.txt (line 3)), name='Pillow')

(cherry picked from commit ce3aba7ffc68b73d64df64c8c9f37eb3b9d4bfda)